#!/usr/bin/env python3
"""
LLM-as-judge scoring over an existing eval JSON.

The similarity metric (difflib.SequenceMatcher) undercounts correct-but-
differently-worded code. This script rescores each record with Claude Haiku
as a semantic judge, producing a second metric that measures correctness +
convention adherence rather than token overlap.

Usage:
    python llm_judge.py <eval.json>                # uses `claude -p` CLI (Claude Code auth)
    ANTHROPIC_API_KEY=sk-... python llm_judge.py <eval.json>   # uses SDK if key set

Output:
    Writes <eval>_llmjudge.json alongside the source with judge scores + the
    same summary structure (avg_score, band_counts, convention_breakdown)
    computed on the judge metric instead of similarity.
"""

import json
import os
import re
import subprocess
import sys
import time
from collections import defaultdict
from pathlib import Path

MODEL = os.environ.get("JUDGE_MODEL", "claude-haiku-4-5-20251001")
USE_SDK = bool(os.environ.get("ANTHROPIC_API_KEY"))

if USE_SDK:
    from anthropic import Anthropic
    client = Anthropic()
else:
    client = None  # we'll shell out to `claude -p` instead

RUBRIC = """You are grading Go code generated by a model against a reference
implementation. Both implement the same function. Return a single float score
from 0.0 to 1.0 judging how well the generated code matches the reference in
*semantic correctness* and *convention adherence*, not string overlap.

Scoring guide:
- 1.0: Fully correct. Same control flow, same conventions applied (error
  wrapping format, identifier patterns, library usage). Only superficial
  differences (variable names, whitespace) remain.
- 0.8: Correct and mostly conventional. One or two convention deviations
  that a code reviewer would ask to fix, but the function would work.
- 0.6: Correct logic, multiple convention deviations. Would need rework.
- 0.4: Partially correct logic, or correct but using wrong libraries /
  patterns for this codebase (e.g. generic Go instead of VA-specific
  idioms like Bearer _%s, ErrRead.Join, sqlfunc.Paging).
- 0.2: Attempts the right thing but has significant logic errors.
- 0.0: Wrong function or unrelated output.

IMPORTANT: The VA-specific conventions you should check for:
- Error wrap: fmt.Errorf("[FunctionName]: %w", err), never bare err
- Sentinel errors: ErrRead.Join(err), &NotFoundError{}, ErrInsertX.Join(err)
- HTTP auth: "Bearer _%s" (underscore mandatory between Bearer and key)
- Retry: plain time.Sleep(backoff), NOT select{case <-time.After...}
- Pagination: sqlfunc.Paging{Limit, Offset}, NOT (page-1)*pageSize
- Logging: *valog.Logger struct field; IsDebugEnabled conditional enrichment
- Template execution: r.template.ExecuteTemplate(&b, "name", params)
- DB queries: r.db.NamedQueryContext, r.db.NamedExecContext
- Context timeout before I/O: context.WithTimeout(ctx, N*time.Second)
- gRPC: status.Errorf with proper codes
- AWS: SDK v1, credentials.NewStaticCredentials, MaxRetries: aws.Int(5)
- Events: eventdealer.WorkflowError; SkipRetry only for non-retryable

Output format: a single JSON object on one line, no other text.
Schema: {"score": <float>, "reason": "<≤30 word explanation>"}
"""


def _build_user_prompt(prompt: str, expected: str, generated: str) -> str:
    return (
        f"## User prompt to the model\n\n{prompt}\n\n"
        f"## Reference (correct) implementation\n\n```go\n{expected}\n```\n\n"
        f"## Generated implementation to grade\n\n```go\n{generated}\n```\n\n"
        f"Return the JSON object now."
    )


def _call_sdk(user_prompt: str) -> str:
    resp = client.messages.create(
        model=MODEL,
        max_tokens=200,
        system=[{"type": "text", "text": RUBRIC, "cache_control": {"type": "ephemeral"}}],
        messages=[{"role": "user", "content": user_prompt}],
    )
    return resp.content[0].text.strip()


def _call_cli(user_prompt: str) -> str:
    combined = f"{RUBRIC}\n\n---\n\n{user_prompt}"
    result = subprocess.run(
        ["claude", "-p", "--model", MODEL, combined],
        capture_output=True, text=True, timeout=120,
    )
    if result.returncode != 0:
        raise RuntimeError(f"claude -p exited {result.returncode}: {result.stderr[:200]}")
    return result.stdout.strip()


def judge_one(prompt: str, expected: str, generated: str) -> tuple[float, str]:
    user = _build_user_prompt(prompt, expected, generated)
    try:
        text = _call_sdk(user) if USE_SDK else _call_cli(user)
    except Exception as e:
        print(f"  [API ERROR] {type(e).__name__}: {e}", file=sys.stderr)
        return 0.0, f"api_error: {type(e).__name__}"
    # tolerate markdown fences if the model added them
    text = re.sub(r"^```(?:json)?\n?|\n?```$", "", text.strip())
    try:
        obj = json.loads(text)
        return float(obj["score"]), str(obj.get("reason", ""))
    except (json.JSONDecodeError, KeyError, ValueError) as e:
        print(f"  [PARSE ERROR] {e}: {text[:120]}", file=sys.stderr)
        return 0.0, f"parse_error: {text[:80]}"


def band(score: float) -> str:
    if score >= 0.8:
        return "EXCELLENT"
    if score >= 0.6:
        return "GOOD"
    if score >= 0.4:
        return "PARTIAL"
    return "POOR"


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        sys.exit(2)

    src = Path(sys.argv[1]).expanduser()
    data = json.loads(src.read_text())
    results = data["results"]

    print(f"Source: {src}")
    print(f"Judge:  {MODEL}")
    print(f"Records: {len(results)}")
    print("=" * 60)

    scored = []
    t0 = time.time()
    for i, r in enumerate(results):
        if r.get("band") == "ERROR" or not r.get("generated"):
            s, reason = 0.0, "error_or_empty"
        else:
            s, reason = judge_one(r["prompt"], r["expected"], r["generated"])
        r2 = dict(r)
        r2["judge_score"] = round(s, 4)
        r2["judge_band"] = band(s)
        r2["judge_reason"] = reason
        scored.append(r2)
        print(f"  [{r2['judge_band']:9s}  {s:.2f}]  {r['id']}  {reason}")

    elapsed = time.time() - t0
    nonerr = [r for r in scored if r["judge_band"] != "ERROR"]
    avg = sum(r["judge_score"] for r in nonerr) / max(len(nonerr), 1)
    band_counts: dict = defaultdict(int)
    for r in scored:
        band_counts[r["judge_band"]] += 1

    conv_scores: dict = defaultdict(list)
    for r in scored:
        for c in r.get("conventions_tested", []):
            conv_scores[c].append(r["judge_score"])
    conv_summary = sorted(
        [{"convention": c, "avg": round(sum(v) / len(v), 3), "n": len(v), "scores": v}
         for c, v in conv_scores.items()],
        key=lambda x: x["avg"],
    )

    out = {
        "meta": {**data.get("meta", {}), "judge_model": MODEL, "scored_at": time.strftime("%Y-%m-%d_%H%M")},
        "similarity_summary": data.get("summary", {}),
        "summary": {
            "avg_score": round(avg, 4),
            "band_counts": dict(band_counts),
            "convention_breakdown": conv_summary,
        },
        "results": scored,
    }
    out_path = src.with_name(src.stem + "_llmjudge.json")
    out_path.write_text(json.dumps(out, indent=2))

    print()
    print("=" * 60)
    print(f"Judge avg:   {avg:.3f}   (similarity was {data['summary']['avg_score']:.3f})")
    print(f"Excellent: {band_counts['EXCELLENT']}  Good: {band_counts['GOOD']}  "
          f"Partial: {band_counts['PARTIAL']}  Poor: {band_counts['POOR']}")
    print(f"Elapsed: {elapsed:.0f}s")
    print(f"Out:    {out_path}")


if __name__ == "__main__":
    main()
